name: CI devops 2026
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - main
      - develop
  pull_request:                       #se lance aussi quand il y a pull request pour les branche main et develop

jobs:
  #1st job
  test-backend:                       #identifiant du job
    runs-on: ubuntu-24.04             #demarre une machine virtuelle linux
    steps:
      #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4     #permet d utiliser plugin deja existant
        #clone le depot dans la machine virtuelle

      #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4   # instllale le kit de developpement java sur la machine irtuelle
        with:
          distribution: 'temurin'
          java-version: 21

      #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn verify clean --file simple-api/pom.xml #sert a executer dans le bash

  # 2nd job - define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin


      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./simple-api                                             #chemin relatif ou se trouve le dockerfile
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-simple-api:latest #name that will be posted on dockerHUb
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}                      # si c'est false alors l'image est build mais n'est aps envoyé sur dockerhub


      - name: Build image and push database
        # DO the same for database
        uses: docker/build-push-action@v6
        with:
          context: ./database                                           #chemin relatif ou se trouve le dockerfile
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-database:latest  #name that will be posted on dockerHUb
          push: ${{ github.ref == 'refs/heads/main' }}                  # si c'est false alors l'image est build mais n'est aps envoyé sur dockerhub

      - name: Build image and push httpd
        # DO the same for httpd
        uses: docker/build-push-action@v6
        with:
          context: ./http-server                                         #chemin relatif ou se trouve le dockerfile
          tags: ${{secrets.DOCKER_USERNAME}}/tp-devops-http-server:latest #name that will be posted on dockerHUb
          push: ${{ github.ref == 'refs/heads/main' }}   # si c'est false alors l'image est build mais n'est aps envoyé sur dockerhub

      - name: Run SonaCloud Analysis

        run: mvn -B verify sonar:sonar \
              -Dsonar.projectKey=matthewcesa_TP2-Devops-GitHubActions \
              -Dsonar.organization=matthewcesa \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}  \
              --file ./simple-api/pom.xml
